version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
orbs:
  cypress: cypress-io/cypress@1
  terraform: circleci/terraform@2.1.0
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  bundle_dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-{{ .Environment.CACHE_VERSION }}

      - run: yarn run build
      - persist_to_workspace:
          root: ./
          paths:
            - .next

  perf:
    docker:
      - image: circleci/node:12.1-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: sudo yarn global add @lhci/cli@0.3.x
      - run:
          name: lhci autorun
          command: |
            lhci autorun
workflows:
  build-and-test:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore: /develop|master/
      - bundle_dependencies:
          requires:
            - checkout_code
          filters:
            branches:
              ignore: /develop|master/p
      - build:
          requires:
            - bundle_dependencies
      - cypress/run:
          yarn: true
      - perf:
          requires:
            - build
          filters:
            branches:
              ignore: /develop|master/
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform/prod
          checkout: true
      - terraform/validate:
          path: ./terraform/prod
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./terraform/prod
          checkout: true
          persist-workspace: true
          var_file: ./terraform/prod/terraform.tfvars
          var: aws_access_key=$AWS_ACCESS_KEY_ID, aws_secret_key=$AWS_SECRET_KEY
          requires:
            - terraform/validate
      - terraform/apply:
          path: ./terraform/prod
          attach-workspace: true
          var_file: ./terraform/prod/terraform.tfvars
          var: aws_access_key=$AWS_ACCESS_KEY_ID, aws_secret_key=$AWS_SECRET_KEY
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
